## IDEA
hoat dong tren khong gian <= 2 chieu (R^2) nhung mot buc anh RGB la khong gian 3 chieu do vay phai reshape lai buc hinh moi tinh toan duoc

## KMEANS

In [210]:
import numpy as np
import matplotlib.pyplot as plt
import PIL as pil

def kmeans(img_1d, k_clusters, max_iter, init_centroids='random'):
    # height <-> row, width <-> col, depth = 3 (RGB)
    height, width, depth = img_1d.shape

    # reshape 3D -> 2D with (height * width) row and each row has 3 elements(RGB)
    reshapedIMG = img_1d.reshape(height * width, depth)

    # initial centroid with k clusters
    if init_centroids == "random":
        centroids = np.random.choice(255, size=(k_clusters, depth)) #2D array with k_cluster row, each row has width element
    elif init_centroids == "in_pixels":
        centroids = reshapedIMG[np.random.choice(height, k_clusters)] 
    
    # find the final centroids
    for i in range(max_iter):
        prevCentroid = centroids
        distance = np.zeros((reshapedIMG.shape[0], k_clusters))

        # find the distances between pixels and centroids
        for k in range(k_clusters):
            distance[:,k] = np.square(np.linalg.norm(reshapedIMG - centroids[k, :], axis=1))

        # min distance
        label = np.argmin(distance, axis=1) 

        # update new centroid
        # initial the centroids array
        centroids = np.zeros((k_clusters, depth)) 
        for k in range(k_clusters):
            centroids[k:] = np.mean(reshapedIMG[label == k,:], axis=0)
        
        # converge
        if np.allclose(prevCentroid, centroids, atol=2):
            break
    
    # assign centroid's value for every pixel
    for k in range(k_clusters):
        reshapedIMG[label == k, :] = centroids[k]

    # reshape the final image array in to 3D
    # reshapedIMG = reshapedIMG.reshape(height * width,)

    return reshapedIMG, centroids
    
def main():
    imgName = input("Enter image name: ")
    img = pil.Image.open(imgName)
    npArray = np.array(img)

    newIMG, centroids = kmeans(npArray, k_clusters=3, max_iter=100, init_centroids="in_pixels")
    plt.savefig()
    print(newIMG)
    # plt.imshow(newIMG)

main()

[[26 13 15]
 [26 13 15]
 [26 13 15]
 ...
 [67 53 64]
 [67 53 64]
 [67 53 64]]
